# Generated by Django 4.1.5 on 2023-02-13 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factotum', '0003_user_service_remove_professionnelservice_service_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soumission',
            name='id_service_Professionnel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='factotum.professionnelservice'),
        ),
    ]
