# Generated by Django 4.1.5 on 2023-02-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factotum', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soumission',
            name='note',
            field=models.IntegerField(),
        ),
    ]
