# Generated by Django 4.1.5 on 2023-02-15 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factotum', '0007_alter_soumission_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_Postal',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('[ABCEGHJKLMNPRSTVXY][0-9][ABCEGHJ-NPRSTV-Z][ ]?|[-]?[0-9][ABCEGHJ-NPRSTV-Z][0-9]', 'Code postal invalide')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
