# Generated by Django 4.1.5 on 2023-02-15 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factotum', '0008_alter_user_code_postal_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soumission',
            name='note',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
