# Generated by Django 4.1.5 on 2023-02-16 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factotum', '0009_alter_soumission_note_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator('^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$', 'Numéro de téléphone invalide')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_Postal',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('[ABCEGHJKLMNPRSTVXY][0-9][ABCEGHJ-NPRSTV-Z][ ]?|[-]?[0-9][ABCEGHJ-NPRSTV-Z][0-9]', "Code postal invalide - assurez-vous que celui-ci soit en majuscule et qu'il n'ait aucune espace")]),
        ),
    ]
