# Generated by Django 4.1.5 on 2023-02-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factotum', '0011_alter_user_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soumission',
            old_name='role',
            new_name='etat',
        ),
    ]
