# Generated by Django 4.1.5 on 2023-02-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factotum', '0012_rename_role_soumission_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soumission',
            name='date_finis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soumission',
            name='date_planification',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='soumission',
            name='description',
            field=models.TextField(),
        ),
    ]
